<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="assignment6_rover_flipped">

  <!-- parameters -->
  <xacro:property name="body_width"  value="0.5"/>
  <xacro:property name="body_length" value="1.0"/>
  <xacro:property name="body_height" value="0.3"/>

  <xacro:property name="front_wheel_radius" value="0.3"/>
  <xacro:property name="front_wheel_length" value="0.25"/>
  <xacro:property name="caster_radius" value="0.2"/>

  <xacro:property name="z_bottom" value="${- body_height/2.0}"/>

  <!-- positions -->
  <xacro:property name="front_x" value="${ body_length/2.0 }"/>  <!-- x=0.5 -->
  <xacro:property name="front_y" value="${ body_width/2.0 }"/>  <!-- y=±0.25 -->
  <xacro:property name="front_z" value="0.0"/>                  <!-- 수직 중앙 -->
  <xacro:property name="caster_x" value="${ -body_length/2.0 + 0.25 }"/> <!-- -0.25 -->
  <xacro:property name="caster_y" value="0.0"/>
  <xacro:property name="caster_z" value="${ z_bottom + caster_radius }"/> <!-- 하단 접촉 -->

  <!-- 색상 -->
  <gazebo reference="base_link"><material>Gazebo/Gray</material></gazebo>
  <gazebo reference="front_left_wheel"><material>Gazebo/Red</material></gazebo>
  <gazebo reference="front_right_wheel"><material>Gazebo/Red</material></gazebo>
  <gazebo reference="rear_center_caster"><material>Gazebo/Black</material></gazebo>

  <!-- world_link: 전체 180도 회전 -->
  <link name="world_link"/>
  <joint name="flip_joint" type="fixed">
    <parent link="world_link"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="3.1416 0 0"/>   <!-- X축 기준 180° 뒤집기 -->
  </joint>

  <!-- chassis -->
  <link name="base_link">
    <visual>
      <geometry><box size="${body_length} ${body_width} ${body_height}"/></geometry>
    </visual>
    <collision>
      <geometry><box size="${body_length} ${body_width} ${body_height}"/></geometry>
    </collision>
    <inertial>
      <mass value="15"/>
      <inertia ixx="0.10" iyy="0.10" izz="0.10" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <!-- front wheel macro -->
  <xacro:macro name="front_wheel" params="name x y z radius length">
    <link name="${name}">
      <visual>
        <geometry><cylinder radius="${radius}" length="${length}"/></geometry>
        <origin rpy="1.5707 0 0"/>
      </visual>
      <collision>
        <geometry><cylinder radius="${radius}" length="${length}"/></geometry>
        <origin rpy="1.5707 0 0"/>
      </collision>
      <inertial>
        <mass value="1.0"/>
        <inertia ixx="0.01" iyy="0.01" izz="0.01" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>
    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child  link="${name}"/>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:front_wheel name="front_left_wheel"
                     x="${front_x}" y="${ front_y}" z="${front_z}"
                     radius="${front_wheel_radius}" length="${front_wheel_length}"/>
  <xacro:front_wheel name="front_right_wheel"
                     x="${front_x}" y="${-front_y}" z="${front_z}"
                     radius="${front_wheel_radius}" length="${front_wheel_length}"/>

  <!-- caster -->
  <link name="rear_center_caster">
    <visual><geometry><sphere radius="${caster_radius}"/></geometry></visual>
    <collision><geometry><sphere radius="${caster_radius}"/></geometry></collision>
    <inertial>
      <mass value="0.3"/>
      <inertia ixx="0.005" iyy="0.005" izz="0.005" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>
  <joint name="rear_center_caster_joint" type="continuous">
    <parent link="base_link"/>
    <child  link="rear_center_caster"/>
    <origin xyz="${caster_x} ${caster_y} ${caster_z}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

</robot>
