<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="simple_rover">
  <xacro:include filename="$(find urdf_tutorial)/urdf/camera.urdf.xacro" />
  <xacro:property name="wheel_separation" value="0.3" />
  <xacro:property name="wheel_radius" value="0.3" />
  <xacro:property name="caster_wheel_radius" value="0.2" />
  <xacro:property name="wheel_width" value="0.25" />
  <xacro:property name="body_width" value="0.5" />
  <xacro:property name="body_length" value="1.0" />
  <xacro:property name="body_height" value="0.3" />

  <xacro:normal_camera robot_name="rover">
  </xacro:normal_camera>

  <gazebo reference="base_link">
    <material>Gazebo/White</material>
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
  </gazebo>

  <gazebo reference="right_wheel">
    <material>Gazebo/Red</material>
    <mu1>0.84</mu1>
    <mu2>0.84</mu2>
  </gazebo>

  <gazebo reference="left_wheel">
    <material>Gazebo/Red</material>
    <mu1>0.84</mu1>
    <mu2>0.84</mu2>
  </gazebo>

  <gazebo reference="caster_wheel">
    <material>Gazebo/Black</material>
    <mu1>0.84</mu1>
    <mu2>0.84</mu2>
  </gazebo>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.2 0.4 0.9 1.0"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry> 
    </collision>

    <inertial>
      <mass value="10"/>
      <inertia ixx="1e-3" ixy="0.0" ixz="0.0" iyy="1e-3" iyz="0.0" izz="1e-3"/>
    </inertial>
  </link>

  <link name="left_wheel">
    <visual>
      <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
  
    <inertial>
      <mass value="1"/>
      <inertia ixx="0.145833" ixy="0.0" ixz="0.0" iyy="0.145833" iyz="0.0" izz="0.125"/>
    </inertial>
  </link>

  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="1"/>
      <inertia ixx="0.145833" ixy="0.0" ixz="0.0" iyy="0.145833" iyz="0.0" izz="0.125"/>
    </inertial>  
  </link>

  <link name="caster_wheel">
    <visual>
      <geometry>
        <cylinder radius="${caster_wheel_radius}" length="0.05"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <cylinder radius="${caster_wheel_radius}" length="0.05"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="1"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>  
  </link>

  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
    </collision>

    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="joint_left" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel" />
    <origin xyz="0.375 -0.25 0" rpy="1.5707 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics friction="0.1"/>
  </joint>

  <joint name="joint_right" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="0.375 0.25 0" rpy="1.5707 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics friction="0.1"/>
  </joint>

  <joint name="joint_caster_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <origin xyz="-0.3 0 -0.15" rpy="0 0 0"/>
    <dynamics friction="0.1"/>
  </joint>

  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="-0.45 0 0.15" rpy="0 0 3.1416"/>
    <dynamics friction="0.1"/>
  </joint>

  <gazebo>
    <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
      <left_joint>joint_left</left_joint>
      <right_joint>joint_right</right_joint>
      <wheel_separation>${wheel_separation + wheel_width}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <odom_publish_frequency>30</odom_publish_frequency>
      <max_wheel_torque>20</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>
      <topic>cmd_vel</topic>
      <odom_topic>odom</odom_topic>
      <frame_id>odom</frame_id>
      <child_frame_id>base_link</child_frame_id>
    </plugin>
  </gazebo>

</robot>